name: api-keep

services:

  mysql:
    image: mysql:latest
    container_name: api-keep-mysql
    environment:
      MYSQL_ROOT_PASSWORD: helios
      MYSQL_DATABASE: files
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - api-keep

  rabbitmq:
    image: rabbitmq:management
    container_name: api-keep-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: api-keep
      RABBITMQ_DEFAULT_PASS: api-keep
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api-keep

  redis:
    image: valkey/valkey:latest
    container_name: api-keep-redis
    ports:
      - "6379:6379"
    networks:
      - api-keep

networks:
  api-keep:
    driver: bridge

volumes:
  mysql_data:
