--liquibase formatted sql

--changeset matigfv:10
ALTER TABLE files DROP CONSTRAINT fk_files_parent;
--rollback ALTER TABLE files ADD CONSTRAINT fk_files_parent FOREIGN KEY (parent_id) REFERENCES files (id) ON DELETE CASCADE;

--changeset matigfv:11
DELETE FROM files;
--rollback

--changeset matigfv:12
ALTER TABLE files ALTER COLUMN id DROP DEFAULT;
ALTER TABLE files ALTER COLUMN id TYPE BIGINT USING NULL;
ALTER TABLE files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE files ALTER COLUMN parent_id TYPE BIGINT USING NULL;
--rollback ALTER TABLE files ALTER COLUMN parent_id TYPE UUID USING NULL;
--rollback ALTER TABLE files ALTER COLUMN id DROP IDENTITY IF EXISTS;
--rollback ALTER TABLE files ALTER COLUMN id TYPE UUID USING NULL;
--rollback ALTER TABLE files ALTER COLUMN id SET DEFAULT gen_random_uuid();

--changeset matigfv:13
ALTER TABLE files ADD CONSTRAINT fk_files_parent FOREIGN KEY (parent_id) REFERENCES files (id) ON DELETE CASCADE;
--rollback ALTER TABLE files DROP CONSTRAINT fk_files_parent;
